### ISSUE TITLE
[Missing]: Hollow Knight

### ISSUE THREAD

**Issue by sybenx** [Steve0Greatness/MovedFromFandomDB#19]
### Fandom URL

hollowknight.fandom.com

### New URL

hollowknight.wiki

Can't add a generic issue so tacking it on here, there are many wiki's listed on this site: https://getindie.wiki/listings/

**Comment by Steve0Greatness** [comment]
Thanks for the issue! I'll add it once I'm able.

**Comment by Steve0Greatness** [comment]
You should now be able to use blank issues if you weren't before.
